name: CrossFit Bourbonnais
favicon: null
layout_spectrum: 1
typography_spectrum: 0.79257
title: Become Stronger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#484848'
    - '#7c7c7c'
    - '#a7a7a7'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
