name: CrossFit Bourbonnais
favicon: null
layout_spectrum: 0.8542233461048454
typography_spectrum: 0.2804908100515604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.578239691676572
  lightness: 0.10809595719911158
  saturation: 0.34940951806493104
  rhythmicContrast: 0.538721322780475
purpose: []
